export const FETCH_DATA = 'FETCH_DATA'
export const FETCHING_DATA_SUCCES = 'FETCHING_DATA_SUCCES'
export const FETCHING_DATA_FAILED = 'FETCHING_DATA_FAILED'

export const FOCUS_ATOM = 'FOCUS_ATOM'
export const BLUR_ATOM = 'BLUR_ATOM'

export const ADD_ATOM = "ADD_ATOM"
export const DELETE_ATOM = "DELETE_ATOM"
export const HIDE_CHILDREN = "HIDE_CHILDREN"
export const UNHIDE_CHILDREN = "UNHIDE_CHILDREN"
export const COMPLETE_SUBTREE = "COMPLETE_SUBTREE"
export const UNCOMPLETE_SUBTREE = "UNCOMPLETE_SUBTREE"
export const COMPLETE_ATOM = "COMPLETE_ATOM"
export const UNCOMPLETE_ATOM = "UNCOMPLETE_ATOM"
export const INDENT_SUBTREE = "INDENT_SUBTREE"
export const UNINDENT_SUBTREE = "UNINDENT_SUBTREE"
export const EDIT_ATOM_TITLE = "EDIT_ATOM_TITLE"
export const EDIT_ATOM_NOTES = "EDIT_ATOM_NOTES"